In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path = "/content/test.xlsx"
df_bonus = pd.read_excel(path)

In [ ]:
y_estimé=df_bonus['y_estimé']
y=df_bonus['y']

##un fonction qui permet de calculer lan matrice de confusion :

In [ ]:
T1= np.zeros((3,3))

for i in range(len(y_estimé)):

  if y[i]==1 :
    if y_estimé[i]==y[i] :
      T1[0][0]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==2:
      T1[0][1]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==3:
      T1[0][2]+=1

  if y[i]==2 :
    if y_estimé[i]==y[i] :
      T1[1][1]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==1:
      T1[1][0]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==3:
      T1[1][2]+=1

  if y[i]==3 :
    if y_estimé[i]==y[i] :
      T1[2][2]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==1:
      T1[2][0]+=1

    if y_estimé[i]!=y[i] and y_estimé[i]==2:
      T1[2][1]+=1

print("la matrice de confusion est :")
print(T1)

la matrice de confusion est :
[[24.  0.  0.]
 [ 0. 26.  0.]
 [ 0.  1. 24.]]


In [ ]:
def conf_matrix_values(confusion_matrix):

    metric_matrix = np.zeros((confusion_matrix.shape[0], 4))
    dim = confusion_matrix.shape[0]
    for i in range(dim):
        metric_matrix[i, 0] = confusion_matrix[i, i]
        metric_matrix[i, 1] = np.sum(confusion_matrix[:, :]) - np.sum(confusion_matrix[:, i]) - np.sum(confusion_matrix[i, :]) + confusion_matrix[i, i]
        metric_matrix[i, 2] = np.sum(confusion_matrix[:, i]) - confusion_matrix[i, i]
        metric_matrix[i, 3] = np.sum(confusion_matrix[i, :]) - confusion_matrix[i, i]

    return metric_matrix

metric_matrix = conf_matrix_values(T1)
print("les scores pour  chaque class:")
print(metric_matrix)

les scores pour  chaque class:
[[24. 51.  0.  0.]
 [26. 48.  1.  0.]
 [24. 50.  0.  1.]]


#calcule de  la précision globale et par classe

In [ ]:
Precision=np.zeros(3)
for i in range(3):

  Precision[i]=metric_matrix[i][0]/(metric_matrix[i][0]+metric_matrix[i][2])

print("Précision pour chaque classe est" ,Precision)
print("Précision globale" ,np.mean(Precision))

Précision est [1.         0.96296296 1.        ]
Précision moyenne 0.9876543209876543


## calcule du rappel globale et par classe

In [ ]:
Recall=np.zeros(3)
for i in range(3):

  Recall[i]=metric_matrix[i][0]/(metric_matrix[i][0]+metric_matrix[i][3])

print("rappel pour chaque classe est" ,Recall)
print("rappel globale" ,np.mean(Recall))


rappel est [1.   1.   0.96]
rappel moyenne 0.9866666666666667


##calcule du F_score globale et par classe

In [ ]:
F_mesure=np.zeros(3)
beta=1

for i in range(3):

  F_mesure[i]=(1+beta*beta)*((Recall[i]*Precision[i])/(beta*beta*Precision[i]+Recall[i]))

print("F score pour pour chaque classe est" ,F_mesure)
print("F score  gobale" ,np.mean(F_mesure))

F score pour est [1.         0.98113208 0.97959184]
Fscore  moyenne 0.986907970735464


##Calcul de la précision avec sklearn

In [ ]:
import sklearn.metrics as metrics

print(metrics.classification_report(y, y_estimé))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        24
           2       0.96      1.00      0.98        26
           3       1.00      0.96      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75



D'apres les résultats obtenu on remarque que la marice de confusion nous permet  de voir
facilement si l’algorithme d’apprentissage confond deux classes. Chaque
colonne de la matrice de confusion représente les instances d’une classe estimé,
tandis que chaque linge représente des instances d’une classe réelle.